image: node:latest

stages:
  - build
  - test
  - deploy_frontend
  - deploy_backend


frontend_build:
  stage: build
  script:
    - cd frontend
    - npm install
    - npm run build


backend_build:
  stage: build
  script:
    - cd backend
    - npm install
    - npm run build


deploy_frontend:
  stage: deploy_frontend
  script:
    - cd frontend
    - npm install -g serve
    - serve -s build

deploy_backend:
  stage: deploy_backend
  script:
    - cd backend
    - npm install -g pm2
    - pm2 stop app || true
    - pm2 start app.js
